import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";

import {
  AlertDialogApiTable,
  AlertDialogDemo,
  AlertDialogSlotsTable,
  BadgeApiTable,
  BadgeVariantDemo,
  ButtonGroupApiTable,
  ButtonGroupDemo,
  ButtonApiTable,
  ButtonIconDemo,
  ButtonSizeDemo,
  ButtonStateDemo,
  ButtonVariantDemo,
  CheckboxApiTable,
  CheckboxStateDemo,
  DropdownMenuApiTable,
  DropdownMenuDemo,
  DropdownMenuSlotsTable,
  FieldApiTable,
  FieldDemo,
  FieldSlotsTable,
  InputApiTable,
  InputDemo,
  InputGroupApiTable,
  InputGroupDemo,
  InputGroupSlotsTable,
  ItemApiTable,
  ItemDemo,
  ItemSlotsTable,
  LabelApiTable,
  LabelDemo,
  RadioGroupApiTable,
  RadioGroupDemo,
  SeparatorApiTable,
  SeparatorDemo,
  SkeletonApiTable,
  SkeletonDemo,
  SliderApiTable,
  SliderDemo,
  SwitchApiTable,
  SwitchDemo,
  TextareaApiTable,
  TextareaDemo,
  ToasterApiTable,
  ToasterDemo,
  ToasterUsageGuidance,
  CardActionDemo,
  CardApiTable,
  CardMediaDemo,
  CardSizeDemo,
  CardSlotsTable,
  CardStructureDemo,
  ComponentGrid,
  Guidance,
  SpinnerApiTable,
  SpinnerBasicDemo,
  SpinnerButtonDemo,
  SpinnerColorDemo,
  SpinnerSizeDemo,
} from "@/components/docs";

export function getMDXComponents(components?: MDXComponents) {
  return {
    ...defaultMdxComponents,
    AlertDialogApiTable,
    AlertDialogDemo,
    AlertDialogSlotsTable,
    BadgeApiTable,
    BadgeVariantDemo,
    ButtonGroupApiTable,
    ButtonGroupDemo,
    ButtonApiTable,
    ButtonIconDemo,
    ButtonSizeDemo,
    ButtonStateDemo,
    ButtonVariantDemo,
    CheckboxApiTable,
    CheckboxStateDemo,
    DropdownMenuApiTable,
    DropdownMenuDemo,
    DropdownMenuSlotsTable,
    FieldApiTable,
    FieldDemo,
    FieldSlotsTable,
    InputApiTable,
    InputDemo,
    InputGroupApiTable,
    InputGroupDemo,
    InputGroupSlotsTable,
    ItemApiTable,
    ItemDemo,
    ItemSlotsTable,
    LabelApiTable,
    LabelDemo,
    RadioGroupApiTable,
    RadioGroupDemo,
    SeparatorApiTable,
    SeparatorDemo,
    SkeletonApiTable,
    SkeletonDemo,
    SliderApiTable,
    SliderDemo,
    SwitchApiTable,
    SwitchDemo,
    TextareaApiTable,
    TextareaDemo,
    ToasterApiTable,
    ToasterDemo,
    ToasterUsageGuidance,
    CardActionDemo,
    CardApiTable,
    CardMediaDemo,
    CardSizeDemo,
    CardSlotsTable,
    CardStructureDemo,
    ComponentGrid,
    Guidance,
    SpinnerApiTable,
    SpinnerBasicDemo,
    SpinnerButtonDemo,
    SpinnerColorDemo,
    SpinnerSizeDemo,
    ...components,
  } satisfies MDXComponents;
}

export const useMDXComponents = getMDXComponents;

declare global {
  type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
